### ISSUE TITLE
No effect on Pixel 8 Pro A14 

### ISSUE THREAD

**Issue by juztim** [cuynu/gphotos-unlimited-zygisk#2]
This module doesn't seem to work on the Pixel 8 Pro with the latest Google Photos app

**Comment by KieronQuinn** [comment]
Try taking a photo and having it upload, it should show in the info sheet that it's not taking up any space. For some reason, it doesn't make the info box in the backup menu appear, but does appear to still be working. 

I've not tested it _actually_ works (as in the message is correct and it's genuinely not using space), will need to upload a large video to verify that.

**Comment by KieronQuinn** [comment]
Verified, I uploaded a 918MB video and it had no impact on storage use, so it works fine :)

**Comment by juztim** [comment]
You're right, works fine! Even after removing the module it still works for me somehow

**Comment by PATAPOsha** [comment]
@KieronQuinn @juztim  did you guys reach free 15 GB limit and it still works for you?

**Comment by KieronQuinn** [comment]
I uploaded 50GB two days ago. No usage.
