### ISSUE TITLE
Does it work on OxygenOS A14 ?

### ISSUE THREAD

**Issue by Nuub073** [cuynu/gphotos-unlimited-zygisk#3]
Um, it's a request if you can list the module compatibility for skins other than aosp

**Comment by cuynu** [comment]
try it and see

**Comment by Nuub073** [comment]
> try it and see

thing is, OP doesn't provide a MSM tool to flash roms anymore, So i can't flash any fastboot rom either ,doesn't exist for 11R, if I update to a14, i have no way to go back to a13 n the og pixelify module won't work,but thanks for reply

**Comment by hjyoung1** [comment]
> > try it and see
> 
> thing is, OP doesn't provide a MSM tool to flash roms anymore, So i can't flash any fastboot rom either ,doesn't exist for 11R, if I update to a14, i have no way to go back to a13 n the og pixelify module won't work,but thanks for reply

In Oneplus 11 running OxygenOS A14 module working fine.

**Comment by cuynu** [comment]
works
