### ISSUE TITLE
Module doesn't work on my Pixel 6

### ISSUE THREAD

**Issue by jackhu9527** [cuynu/gphotos-unlimited-zygisk#4]
Had the module installed on Pixel 6 without any issue. Magisk with Zygisk is installed.

I have no idea why the module doesn't work, my Google Photo doesn't show unlimited photo backup at all.  I would appreciate it if you can suggest a direction to look into it, thanks.

**Comment by cuynu** [comment]
This module are easily getting conflict with other modules, try disable some module and see

For mine, it's works fine
Realme C55
Android 13 RUI 4.0 (AOSP should works)
Magisk Delta v26.1 + Zygisk
Google Photos version : `6.60.0.577965617`
![Screenshot_2023-11-05-05-20-46-36_965bbf4d18d205f782c6b8409c5773a4](https://github.com/cuynu/gphotos-unlimited-zygisk/assets/90895715/c04f73bf-bda8-4502-8767-39ddac2280cb)

![Screenshot_2023-11-05-05-22-50-28_965bbf4d18d205f782c6b8409c5773a4](https://github.com/cuynu/gphotos-unlimited-zygisk/assets/90895715/10c3c72a-8477-4688-b421-38eaca581f00)

**Comment by pieotr** [comment]
i have pixel 6 as well and it says in app that files form this pixel are unlimited but after sending them to the clout i can see that it actualy uses my space quota, and below each single photo is how much it witghs even tho it should not

**Comment by jackhu9527** [comment]
> This module are easily getting conflict with other modules, try disable some module and see
> 
> For mine, it's works fine
> Realme C55
> Android 13 RUI 4.0 (AOSP should works)
> Magisk Delta v26.1 + Zygisk
> Google Photos version : `6.60.0.577965617`
> ![Screenshot_2023-11-05-05-20-46-36_965bbf4d18d205f782c6b8409c5773a4](https://github.com/cuynu/gphotos-unlimited-zygisk/assets/90895715/c04f73bf-bda8-4502-8767-39ddac2280cb)
> 
> ![Screenshot_2023-11-05-05-22-50-28_965bbf4d18d205f782c6b8409c5773a4](https://github.com/cuynu/gphotos-unlimited-zygisk/assets/90895715/10c3c72a-8477-4688-b421-38eaca581f00)
> 

Thanks for your response. The issue no longer exists and it seems to work fine for me now.
