### ISSUE TITLE
Doesn't work on Pixel 7

### ISSUE THREAD

**Issue by PATAPOsha** [cuynu/gphotos-unlimited-zygisk#6]
Does not work for me on Pixel 7, Android 13, Photos v6.51.0.561138754
module version: 1.1-stable

I think (but I'm not sure) it used to work at the very beginning when I installed it. At that time, my storage was near 15 GB of free limit, and I was able to back up photos to reach 15.4 GB of total usage. I don't know if that was credit to this app or just a Google bug.

Now, I do have text "This Pixel can back up unlimited photos & videos at no charge" in app, but it does not backup photos. It stuck in infinite loop of trying to upload photo, but it fails.

There is also "Account storage full (100%)" alert.

![telegram-cloud-photo-size-2-5346068135930877348-y](https://github.com/cuynu/gphotos-unlimited-zygisk/assets/14761219/74f598f0-869e-4e96-9df0-7ab365cb6229)

Can somebody confirm that module still works for them? If yes - what device, OS, Photos app version?

Also, can some other Magisk modules or LSPosed modules conflict with this module?

**Comment by cuynu** [comment]
This module are easily getting conflict with other modules, try disable some module and see

For mine, it's works fine
Realme C55
Android 13 RUI 4.0
Magisk Delta v26.1 + Zygisk
Google Photos version : `6.60.0.577965617`
![Screenshot_2023-11-05-05-20-46-36_965bbf4d18d205f782c6b8409c5773a4](https://github.com/cuynu/gphotos-unlimited-zygisk/assets/90895715/c04f73bf-bda8-4502-8767-39ddac2280cb)

![Screenshot_2023-11-05-05-22-50-28_965bbf4d18d205f782c6b8409c5773a4](https://github.com/cuynu/gphotos-unlimited-zygisk/assets/90895715/10c3c72a-8477-4688-b421-38eaca581f00)

**Comment by PATAPOsha** [comment]
I don't know how, but it fixed by itself.
Maybe after installing https://github.com/chiteroman/PlayIntegrityFix/ (last change that I made to phone).
I still get "Account storage full (100%)" alert message. But backup just works.
