### ISSUE TITLE
Not working on Pixel 8 Pro

### ISSUE THREAD

**Issue by gamerkonks** [cuynu/gphotos-unlimited-zygisk#7]
Google Pixel 8 Pro
Module Version: 1.1-stable
Google Photos Version 6.60.0.577965617
Android 14 UD1A.231105.004
Google Play System Update 1 October 2023
Magisk 26.4 (26400)
Zygisk enabled.
No other modules enabled.

I've tried clearing Google Photos storage and cache.
![photos](https://github.com/cuynu/gphotos-unlimited-zygisk/assets/14312140/688a5545-46de-4e2c-b909-7bb1496c0264)

**Comment by castorwong** [comment]
Please give Photos App all the premisions. then go to Magisk manager turn the modlue off, reboot, turn the module on, reboot , do this several times and it will work ,I dont know why, my Samsung did 8 times reboots, finally worked

**Comment by redondo-se** [comment]
> Seems to be working actually. Doesn't display the "This Pixel can back up unlimited photos & videos at no charge" as expected, but the images that are backed up display the message "This item doesn't take up space in your account storage."

Does applying this mod break other pixel features like best take or magic eraser?

**Comment by gamerkonks** [comment]
No, everything seems to be working fine.
