### ISSUE TITLE
Does this change the fingerprint?

### ISSUE THREAD

**Issue by Pirateguybrush** [cuynu/gphotos-unlimited-zygisk#9]
Hey there,

Will this change the device fingerprint?  I'm using a spoof to allow wallet to work on my rooted device, but it relies on a specific fingerprint.  Can I use this module without it breaking the fingerprint/wallet side of things?

**Comment by regix1** [comment]
no, I'm using it with a custom PIF and have no issues.

**Comment by cuynu** [comment]
no its just hook gphotos app
